MERGE dbo.LanguageCulture AS TARGET
USING (VALUES (1, 'af-ZA',       'Afrikaans (South Africa)',                                        'af',  'Afrikaans (Suid Afrika)'),
              (1, 'am-ET',       'Amharic (Ethiopia)',                                              'am',  'አማርኛ (ኢትዮጵያ)'),
              (1, 'ar-AE',       'Arabic (U.A.E.)',                                                 'ar',  'العربية (الإمارات العربية المتحدة)'),
              (1, 'ar-BH',       'Arabic (Bahrain)',                                                'ar',  'العربية (البحرين)'),
              (1, 'ar-DZ',       'Arabic (Algeria)',                                                'ar',  'العربية (الجزائر)'),
              (1, 'ar-EG',       'Arabic (Egypt)',                                                  'ar',  'العربية (مصر)'),
              (1, 'ar-IQ',       'Arabic (Iraq)',                                                   'ar',  'العربية (العراق)'),
              (1, 'ar-JO',       'Arabic (Jordan)',                                                 'ar',  'العربية (الأردن)'),
              (1, 'ar-KW',       'Arabic (Kuwait)',                                                 'ar',  'العربية (الكويت)'),
              (1, 'ar-LB',       'Arabic (Lebanon)',                                                'ar',  'العربية (لبنان)'),
              (1, 'ar-LY',       'Arabic (Libya)',                                                  'ar',  'العربية (ليبيا)'),
              (1, 'ar-MA',       'Arabic (Morocco)',                                                'ar',  'العربية (المملكة المغربية)'),
              (1, 'ar-OM',       'Arabic (Oman)',                                                   'ar',  'العربية (عمان)'),
              (1, 'ar-QA',       'Arabic (Qatar)',                                                  'ar',  'العربية (قطر)'),
              (1, 'ar-SA',       'Arabic (Saudi Arabia)',                                           'ar',  'العربية (المملكة العربية السعودية)'),
              (1, 'ar-SY',       'Arabic (Syria)',                                                  'ar',  'العربية (سوريا)'),
              (1, 'ar-TN',       'Arabic (Tunisia)',                                                'ar',  'العربية (تونس)'),
              (1, 'ar-YE',       'Arabic (Yemen)',                                                  'ar',  'العربية (اليمن)'),
              (1, 'arn-CL',      'Mapudungun (Chile)',                                              'arn', 'Mapudungun (Chile)'),
              (1, 'as-IN',       'Assamese (India)',                                                'as',  'অসমীয়া (ভাৰত)'),
              (1, 'az-Cyrl-AZ',  'Azeri (Cyrillic) (Azerbaijan)',                                   'az',  'Азәрбајҹан (Азәрбајҹан)'),
              (1, 'az-Latn-AZ',  'Azeri (Latin) (Azerbaijan)',                                      'az',  'Azərbaycan­ılı (Azərbaycanca)'),
              (1, 'ba-RU',       'Bashkir (Russia)',                                                'ba',  'Башҡорт (Россия)'),
              (1, 'be-BY',       'Belarusian (Belarus)',                                            'be',  'Беларускі (Беларусь)'),
              (1, 'bg-BG',       'Bulgarian (Bulgaria)',                                            'bg',  'български (България)'),
              (1, 'bn-BD',       'Bengali (Bangladesh)',                                            'bn',  'বাংলা (বাংলাদেশ)'),
              (1, 'bn-IN',       'Bengali (India)',                                                 'bn',  'বাংলা (ভারত)'),
              (1, 'bo-CN',       'Tibetan (People''s Republic of China)',                           'bo',  'བོད་ཡིག (ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ།)'),
              (1, 'br-FR',       'Breton (France)',                                                 'br',  'brezhoneg (Frañs)'),
              (1, 'bs-Cyrl-BA',  'Bosnian (Cyrillic) (Bosnia and Herzegovina)',                     'bs',  'босански (Босна и Херцеговина)'),
              (1, 'bs-Latn-BA',  'Bosnian (Latin) (Bosnia and Herzegovina)',                        'bs',  'bosanski (Bosna i Hercegovina)'),
              (1, 'ca-ES',       'Catalan (Catalan)',                                               'ca',  'català (català)'),
              (1, 'co-FR',       'Corsican (France)',                                               'co',  'Corsu (France)'),
              (1, 'cs-CZ',       'Czech (Czech Republic)',                                          'cs',  'čeština (Česká republika)'),
              (1, 'cy-GB',       'Welsh (United Kingdom)',                                          'cy',  'Cymraeg (y Deyrnas Unedig)'),
              (1, 'da-DK',       'Danish (Denmark)',                                                'da',  'dansk (Danmark)'),
              (1, 'de-AT',       'German (Austria)',                                                'de',  'Deutsch (Österreich)'),
              (1, 'de-CH',       'German (Switzerland)',                                            'de',  'Deutsch (Schweiz)'),
              (1, 'de-DE',       'German (Germany)',                                                'de',  'Deutsch (Deutschland)'),
              (1, 'de-LI',       'German (Liechtenstein)',                                          'de',  'Deutsch (Liechtenstein)'),
              (1, 'de-LU',       'German (Luxembourg)',                                             'de',  'Deutsch (Luxemburg)'),
              (1, 'dsb-DE',      'Lower Sorbian (Germany)',                                         'dsb', 'dolnoserbšćina (Nimska)'),
              (1, 'dv-MV',       'Divehi (Maldives)',                                               'dv',  'ދިވެހިބަސް (ދިވެހި ރާއްޖެ)'),
              (1, 'el-GR',       'Greek (Greece)',                                                  'el',  'ελληνικά (Ελλάδα)'),
              (1, 'en-029',      'English (Caribbean)',                                             'en',  'English (Caribbean)'),
              (1, 'en-AU',       'English (Australia)',                                             'en',  'English (Australia)'),
              (1, 'en-BZ',       'English (Belize)',                                                'en',  'English (Belize)'),
              (1, 'en-CA',       'English (Canada)',                                                'en',  'English (Canada)'),
              (1, 'en-GB',       'English (United Kingdom)',                                        'en',  'English (United Kingdom)'),
              (1, 'en-IE',       'English (Ireland)',                                               'en',  'English (Eire)'),
              (1, 'en-IN',       'English (India)',                                                 'en',  'English (India)'),
              (1, 'en-JM',       'English (Jamaica)',                                               'en',  'English (Jamaica)'),
              (1, 'en-MY',       'English (Malaysia)',                                              'en',  'English (Malaysia)'),
              (1, 'en-NZ',       'English (New Zealand)',                                           'en',  'English (New Zealand)'),
              (1, 'en-PH',       'English (Republic of the Philippines)',                           'en',  'English (Philippines)'),
              (1, 'en-SG',       'English (Singapore)',                                             'en',  'English (Singapore)'),
              (1, 'en-TT',       'English (Trinidad and Tobago)',                                   'en',  'English (Trinidad y Tobago)'),
              (1, 'en-US',       'English (United States)',                                         'en',  'English (United States)'),
              (1, 'en-ZA',       'English (South Africa)',                                          'en',  'English (South Africa)'),
              (1, 'en-ZW',       'English (Zimbabwe)',                                              'en',  'English (Zimbabwe)'),
              (1, 'es-AR',       'Spanish (Argentina)',                                             'es',  'Español (Argentina)'),
              (1, 'es-BO',       'Spanish (Bolivia)',                                               'es',  'Español (Bolivia)'),
              (1, 'es-CL',       'Spanish (Chile)',                                                 'es',  'Español (Chile)'),
              (1, 'es-CO',       'Spanish (Colombia)',                                              'es',  'Español (Colombia)'),
              (1, 'es-CR',       'Spanish (Costa Rica)',                                            'es',  'Español (Costa Rica)'),
              (1, 'es-DO',       'Spanish (Dominican Republic)',                                    'es',  'Español (República Dominicana)'),
              (1, 'es-EC',       'Spanish (Ecuador)',                                               'es',  'Español (Ecuador)'),
              (1, 'es-ES',       'Spanish (Spain)',                                                 'es',  'español (España)'),
              (1, 'es-GT',       'Spanish (Guatemala)',                                             'es',  'Español (Guatemala)'),
              (1, 'es-HN',       'Spanish (Honduras)',                                              'es',  'Español (Honduras)'),
              (1, 'es-MX',       'Spanish (Mexico)',                                                'es',  'Español (México)'),
              (1, 'es-NI',       'Spanish (Nicaragua)',                                             'es',  'Español (Nicaragua)'),
              (1, 'es-PA',       'Spanish (Panama)',                                                'es',  'Español (Panamá)'),
              (1, 'es-PE',       'Spanish (Peru)',                                                  'es',  'Español (Perú)'),
              (1, 'es-PR',       'Spanish (Puerto Rico)',                                           'es',  'Español (Puerto Rico)'),
              (1, 'es-PY',       'Spanish (Paraguay)',                                              'es',  'Español (Paraguay)'),
              (1, 'es-SV',       'Spanish (El Salvador)',                                           'es',  'Español (El Salvador)'),
              (1, 'es-US',       'Spanish (United States)',                                         'es',  'Español (Estados Unidos)'),
              (1, 'es-UY',       'Spanish (Uruguay)',                                               'es',  'Español (Uruguay)'),
              (1, 'es-VE',       'Spanish (Venezuela)',                                             'es',  'Español (Republica Bolivariana de Venezuela)'),
              (1, 'et-EE',       'Estonian (Estonia)',                                              'et',  'eesti (Eesti)'),
              (1, 'eu-ES',       'Basque (Basque)',                                                 'eu',  'euskara (euskara)'),
              (1, 'fa-IR',       'Persian (Iran)',                                                  'fa',  'فارسى (ايران)'),
              (1, 'fi-FI',       'Finnish (Finland)',                                               'fi',  'suomi (Suomi)'),
              (1, 'fil-PH',      'Filipino (Philippines)',                                          'fil', 'Filipino (Pilipinas)'),
              (1, 'fo-FO',       'Faroese (Faroe Islands)',                                         'fo',  'føroyskt (Føroyar)'),
              (1, 'fr-BE',       'French (Belgium)',                                                'fr',  'français (Belgique)'),
              (1, 'fr-CA',       'French (Canada)',                                                 'fr',  'français (Canada)'),
              (1, 'fr-CH',       'French (Switzerland)',                                            'fr',  'français (Suisse)'),
              (1, 'fr-FR',       'French (France)',                                                 'fr',  'français (France)'),
              (1, 'fr-LU',       'French (Luxembourg)',                                             'fr',  'français (Luxembourg)'),
              (1, 'fr-MC',       'French (Principality of Monaco)',                                 'fr',  'français (Principauté de Monaco)'),
              (1, 'fy-NL',       'Frisian (Netherlands)',                                           'fy',  'Frysk (Nederlân)'),
              (1, 'ga-IE',       'Irish (Ireland)',                                                 'ga',  'Gaeilge (Éire)'),
              (1, 'gd-GB',       'Scottish Gaelic (United Kingdom)',                                'gd',  'Gàidhlig (An Rìoghachd Aonaichte)'),
              (1, 'gl-ES',       'Galician (Galician)',                                             'gl',  'galego (galego)'),
              (1, 'gsw-FR',      'Alsatian (France)',                                               'gsw', 'Elsässisch (Frànkrisch)'),
              (1, 'gu-IN',       'Gujarati (India)',                                                'gu',  'ગુજરાતી (ભારત)'),
              (1, 'ha-Latn-NG',  'Hausa (Latin) (Nigeria)',                                         'ha',  'Hausa (Nigeria)'),
              (1, 'he-IL',       'Hebrew (Israel)',                                                 'he',  'עברית (ישראל)'),
              (1, 'hi-IN',       'Hindi (India)',                                                   'hi',  'हिंदी (भारत)'),
              (1, 'hr-BA',       'Croatian (Latin) (Bosnia and Herzegovina)',                       'hr',  'hrvatski (Bosna i Hercegovina)'),
              (1, 'hr-HR',       'Croatian (Croatia)',                                              'hr',  'hrvatski (Hrvatska)'),
              (1, 'hsb-DE',      'Upper Sorbian (Germany)',                                         'hsb', 'hornjoserbšćina (Němska)'),
              (1, 'hu-HU',       'Hungarian (Hungary)',                                             'hu',  'magyar (Magyarország)'),
              (1, 'hy-AM',       'Armenian (Armenia)',                                              'hy',  'Հայերեն (Հայաստան)'),
              (1, 'id-ID',       'Indonesian (Indonesia)',                                          'id',  'Bahasa Indonesia (Indonesia)'),
              (1, 'ig-NG',       'Igbo (Nigeria)',                                                  'ig',  'Igbo (Nigeria)'),
              (1, 'ii-CN',       'Yi (People''s Republic of China)',                                'ii',  'ꆈꌠꁱꂷ (ꍏꉸꏓꂱꇭꉼꇩ)'),
              (1, 'is-IS',       'Icelandic (Iceland)',                                             'is',  'íslenska (Ísland)'),
              (1, 'it-CH',       'Italian (Switzerland)',                                           'it',  'italiano (Svizzera)'),
              (1, 'it-IT',       'Italian (Italy)',                                                 'it',  'italiano (Italia)'),
              (1, 'iu-Cans-CA',  'Inuktitut (Syllabics) (Canada)',                                  'iu',  'ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕ)'),
              (1, 'iu-Latn-CA',  'Inuktitut (Latin) (Canada)',                                      'iu',  'Inuktitut (kanata)'),
              (1, 'ja-JP',       'Japanese (Japan)',                                                'ja',  '日本語 (日本)'),
              (1, 'ka-GE',       'Georgian (Georgia)',                                              'ka',  'ქართული (საქართველო)'),
              (1, 'kk-KZ',       'Kazakh (Kazakhstan)',                                             'kk',  'Қазақ (Қазақстан)'),
              (1, 'kl-GL',       'Greenlandic (Greenland)',                                         'kl',  'kalaallisut (Kalaallit Nunaat)'),
              (1, 'km-KH',       'Khmer (Cambodia)',                                                'km',  'ខ្មែរ (កម្ពុជា)'),
              (1, 'kn-IN',       'Kannada (India)',                                                 'kn',  'ಕನ್ನಡ (ಭಾರತ)'),
              (1, 'ko-KR',       'Korean (Korea)',                                                  'ko',  '한국어 (대한민국)'),
              (1, 'kok',         'Konkani',                                                         'kok', 'कोंकणी'),
              (1, 'kok-IN',      'Konkani (India)',                                                 'kok', 'कोंकणी (भारत)'),
              (1, 'ky-KG',       'Kyrgyz (Kyrgyzstan)',                                             'kok', 'Кыргыз (Кыргызстан)'),
              (1, 'lb-LU',       'Luxembourgish (Luxembourg)',                                      'lb',  'Lëtzebuergesch (Luxembourg)'),
              (1, 'lo-LA',       'Lao (Lao P.D.R.)',                                                'lo',  'ລາວ (ສ.ປ.ປ. ລາວ)'),
              (1, 'lt-LT',       'Lithuanian (Lithuania)',                                          'lt',  'lietuvių (Lietuva)'),
              (1, 'lv-LV',       'Latvian (Latvia)',                                                'lv',  'latviešu (Latvija)'),
              (1, 'mi-NZ',       'Maori (New Zealand)',                                             'mi',  'Reo Māori (Aotearoa)'),
              (1, 'mk-MK',       'Macedonian (Former Yugoslav Republic of Macedonia)',              'mk',  'македонски јазик (Македонија)'),
              (1, 'ml-IN',       'Malayalam (India)',                                               'ml',  'മലയാളം (ഭാരതം)'),
              (1, 'mn-MN',       'Mongolian (Cyrillic) (Mongolia)',                                 'mn',  'Монгол хэл (Монгол улс)'),
              (1, 'mn-Mong-CN',  'Mongolian (Traditional Mongolian) (People''s Republic of China)', 'mn',  'ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ (ᠪᠦᠭᠦᠳᠡ ᠨᠠᠢᠷᠠᠮᠳᠠᠬᠤ ᠳᠤᠮᠳᠠᠳᠤ ᠠᠷᠠᠳ ᠣᠯᠣᠰ)'),
              (1, 'moh-CA',      'Mohawk (Canada)',                                                 'moh', 'Kanien''kéha (Canada)'),
              (1, 'mr-IN',       'Marathi (India)',                                                 'mr',  'मराठी (भारत)'),
              (1, 'ms-BN',       'Malay (Brunei Darussalam)',                                       'ms',  'Bahasa Malaysia (Brunei Darussalam)'),              
              (1, 'ms-MY',       'Malay (Malaysia)',                                                'ms',  'Bahasa Malaysia (Malaysia)'),
              (1, 'mt-MT',       'Maltese (Malta)',                                                 'mt',  'Malti (Malta)'),
              (1, 'nb-NO',       'Norwegian, Bokmål (Norway)',                                      'nb',  'norsk, bokmål (Norge)'),
              (1, 'ne-NP',       'Nepali (Nepal)',                                                  'ne',  'नेपाली (नेपाल)'),
              (1, 'nl-BE',       'Dutch (Belgium)',                                                 'nl',  'Nederlands (België)'),
              (1, 'nl-NL',       'Dutch (Netherlands)',                                             'nl',  'Nederlands (Nederland)'),
              (1, 'nn-NO',       'Norwegian, Nynorsk (Norway)',                                     'nn',  'norsk, nynorsk (Noreg)'),
              (1, 'nso-ZA',      'Sesotho sa Leboa (South Africa)',                                 'nso', 'Sesotho sa Leboa (Afrika Borwa)'),
              (1, 'oc-FR',       'Occitan (France)',                                                'oc',  'Occitan (França)'),
              (1, 'or-IN',       'Oriya (India)',                                                   'or',  'ଓଡ଼ିଆ (ଭାରତ)'),
              (1, 'pa-IN',       'Punjabi (India)',                                                 'pa',  'ਪੰਜਾਬੀ (ਭਾਰਤ)'),
              (1, 'pl-PL',       'Polish (Poland)',                                                 'pl',  'polski (Polska)'),
              (1, 'prs-AF',      'Dari (Afghanistan)',                                              'prs', 'درى (افغانستان)'),
              (1, 'ps-AF',       'Pashto (Afghanistan)',                                            'ps',  'پښتو (افغانستان)'),
              (1, 'pt-BR',       'Portuguese (Brazil)',                                             'pt',  'Português (Brasil)'),
              (1, 'pt-PT',       'Portuguese (Portugal)',                                           'pt',  'português (Portugal)'),
              (1, 'qut-GT',      'K''iche (Guatemala)',                                             'qut', 'K''iche (Guatemala)'),
              (1, 'quz-BO',      'Quechua (Bolivia)',                                               'quz', 'runasimi (Bolivia Suyu)'),
              (1, 'quz-EC',      'Quechua (Ecuador)',                                               'quz', 'runasimi (Ecuador Suyu)'),
              (1, 'quz-PE',      'Quechua (Peru)',                                                  'quz', 'runasimi (Peru Suyu)'),
              (1, 'rm-CH',       'Romansh (Switzerland)',                                           'rm',  'Rumantsch (Svizra)'),
              (1, 'ro-RO',       'Romanian (Romania)',                                              'ro',  'română (România)'),
              (1, 'ru-RU',       'Russian (Russia)',                                                'ru',  'русский (Россия)'),
              (1, 'rw-RW',       'Kinyarwanda (Rwanda)',                                            'rw',  'Kinyarwanda (Rwanda)'),
              (1, 'sa-IN',       'Sanskrit (India)',                                                'sa',  'संस्कृत (भारतम्)'),
              (1, 'sah-RU',      'Yakut (Russia)',                                                  'sah', 'саха (Россия)'),
              (1, 'se-FI',       'Sami (Northern) (Finland)',                                       'se',  'davvisámegiella (Suopma)'),
              (1, 'se-NO',       'Sami (Northern) (Norway)',                                        'se',  'davvisámegiella (Norga)'),
              (1, 'se-SE',       'Sami (Northern) (Sweden)',                                        'se',  'davvisámegiella (Ruoŧŧa)'),
              (1, 'si-LK',       'Sinhala (Sri Lanka)',                                             'si',  'සිංහ (ශ්‍රී ලංකා)'),
              (1, 'sk-SK',       'Slovak (Slovakia)',                                               'sk',  'slovenčina (Slovenská republika)'),
              (1, 'sl-SI',       'Slovenian (Slovenia)',                                            'sl',  'slovenski (Slovenija)'),
              (1, 'sma-NO',      'Sami (Southern) (Norway)',                                        'sma', 'åarjelsaemiengiele (Nöörje)'),
              (1, 'sma-SE',      'Sami (Southern) (Sweden)',                                        'sma', 'åarjelsaemiengiele (Sveerje)'),
              (1, 'smj-NO',      'Sami (Lule) (Norway)',                                            'smj', 'julevusámegiella (Vuodna)'),
              (1, 'smj-SE',      'Sami (Lule) (Sweden)',                                            'smj', 'julevusámegiella (Svierik)'),
              (1, 'smn-FI',      'Sami (Inari) (Finland)',                                          'smn', 'sämikielâ (Suomâ)'),
              (1, 'sms-FI',      'Sami (Skolt) (Finland)',                                          'sms', 'sääm´ǩiõll (Lää´ddjânnam)'),
              (1, 'sq-AL',       'Albanian (Albania)',                                              'sq',  'shqipe (Shqipëria)'),
              (1, 'sr-Cyrl-BA',  'Serbian (Cyrillic) (Bosnia and Herzegovina)',                     'sr',  'српски (Босна и Херцеговина)'),
              (1, 'sr-Cyrl-CS',  'Serbian (Cyrillic) (Serbia and Montenegro (Former))',             'sr',  'српски (Србија и Црна Гора (Претходно))'),
              (1, 'sr-Cyrl-ME',  'Serbian (Cyrillic) (Montenegro)',                                 'sr',  'српски (Црна Гора)'),
              (1, 'sr-Cyrl-RS',  'Serbian (Cyrillic) (Serbia)',                                     'sr',  'српски (Србија)'),
              (1, 'sr-Latn-BA',  'Serbian (Latin) (Bosnia and Herzegovina)',                        'sr',  'srpski (Bosna i Hercegovina)'),
              (1, 'sr-Latn-CS',  'Serbian (Latin) (Serbia and Montenegro (Former))',                'sr',  'srpski (Srbija i Crna Gora (Prethodno))'),
              (1, 'sr-Latn-ME',  'Serbian (Latin) (Montenegro)',                                    'sr',  'srpski (Crna Gora)'),
              (1, 'sr-Latn-RS',  'Serbian (Latin) (Serbia)',                                        'sr',  'srpski (Srbija)'),
              (1, 'sv-FI',       'Swedish (Finland)',                                               'sv',  'svenska (Finland)'),
              (1, 'sv-SE',       'Swedish (Sweden)',                                                'sv',  'svenska (Sverige)'),
              (1, 'sw-KE',       'Kiswahili (Kenya)',                                               'sw',  'Kiswahili (Kenya)'),
              (1, 'syr-SY',      'Syriac (Syria)',                                                  'syr', 'ܣܘܪܝܝܐ (سوريا)'),
              (1, 'ta-IN',       'Tamil (India)',                                                   'ta',  'தமிழ் (இந்தியா)'),
              (1, 'te-IN',       'Telugu (India)',                                                  'te',  'తెలుగు (భారత దేశం)'),
              (1, 'tg-Cyrl-TJ',  'Tajik (Cyrillic) (Tajikistan)',                                   'tg',  'Тоҷикӣ (Тоҷикистон)'),
              (1, 'th-TH',       'Thai (Thailand)',                                                 'th',  'ไทย (ไทย)'),
              (1, 'tk-TM',       'Turkmen (Turkmenistan)',                                          'tk',  'türkmençe (Türkmenistan)'),
              (1, 'tn-ZA',       'Setswana (South Africa)',                                         'tn',  'Setswana (Aforika Borwa)'),
              (1, 'tr-TR',       'Turkish (Turkey)',                                                'tr',  'Türkçe (Türkiye)'),
              (1, 'tt-RU',       'Tatar (Russia)',                                                  'tt',  'Татар (Россия)'),
              (1, 'tzm-Latn-DZ', 'Tamazight (Latin) (Algeria)',                                     'tzm', 'Tamazight (Djazaïr)'),
              (1, 'ug-CN',       'Uyghur (People''s Republic of China)',                            'ug',  'ئۇيغۇرچە (جۇڭخۇا خەلق جۇمھۇرىيىتى)'),
              (1, 'uk-UA',       'Ukrainian (Ukraine)',                                             'uk',  'україньска (Україна)'),
              (1, 'ur-PK',       'Urdu (Islamic Republic of Pakistan)',                             'ur',  'اُردو (پاکستان)'),
              (1, 'uz-Cyrl-UZ',  'Uzbek (Cyrillic) (Uzbekistan)',                                   'uz',  'Ўзбек (Ўзбекистон)'),
              (1, 'uz-Latn-UZ',  'Uzbek (Latin) (Uzbekistan)',                                      'uz',  'U''zbek (U''zbekiston Respublikasi)'),
              (1, 'vi-VN',       'Vietnamese (Vietnam)',                                            'vi',  'Tiếng Việt (Việt Nam)'),
              (1, 'wo-SN',       'Wolof (Senegal)',                                                 'wo',  'Wolof (Sénégal)'),
              (1, 'xh-ZA',       'isiXhosa (South Africa)',                                         'xh',  'isiXhosa (uMzantsi Afrika)'),
              (1, 'yo-NG',       'Yoruba (Nigeria)',                                                'yo',  'Yoruba (Nigeria)'),
              (1, 'zh-CHS',      'Chinese (Simplified)',                                            'zh',  '中文(简体)'),
              (1, 'zh-CHT',      'Chinese (Traditional)',                                           'zh',  '中文(繁體)'),
              (1, 'zh-CN',       'Chinese (People''s Republic of China)',                           'zh',  '中文(中华人民共和国)'),
              (1, 'zh-HK',       'Chinese (Hong Kong S.A.R.)',                                      'zh',  '中文(香港特别行政區)'),
              (1, 'zh-MO',       'Chinese (Macao S.A.R.)',                                          'zh',  '中文(澳門特别行政區)'),
              (1, 'zh-SG',       'Chinese (Singapore)',                                             'zh',  '中文(新加坡)'),
              (1, 'zh-TW',       'Chinese (Taiwan)',                                                'zh',  '中文(台灣)'),
              (1, 'zu-ZA',       'isiZulu (South Africa)',                                          'zu',  'isiZulu (iNingizimu Afrika)'))
AS SOURCE (IsActive,
           LanguageCultureId,
           EnglishName,
           LanguageCode,
           NativeName)
ON TARGET.LanguageCultureId = SOURCE.LanguageCultureId
WHEN MATCHED THEN UPDATE SET TARGET.LanguageCode       = SOURCE.LanguageCode,
                             TARGET.EnglishName        = SOURCE.EnglishName,
                             TARGET.NativeName         = SOURCE.NativeName,
                             TARGET.IsActive           = SOURCE.IsActive
WHEN NOT MATCHED THEN INSERT (LanguageCode,
                              LanguageCultureId,
                              EnglishName,
                              NativeName,
                              IsActive)
                      VALUES (SOURCE.LanguageCode,
                              SOURCE.LanguageCultureId,
                              SOURCE.EnglishName,
                              SOURCE.NativeName,
                              SOURCE.IsActive);